openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /login:
    post:
      tags:
        - login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: string
  /users:
    get:
      summary: Get list of users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          description: The name of the user.
        password:
          type: string
          format: password
          description: The email address of the user.
